### PR TITLE
docs(install): use python -m pip to ditinguish Python version

### PR DESCRIPTION
**Pull request by tpoisonooo**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix python requirements install description to avoid Python version problem. They are different:
```shell
(base) khj@khj:~/mmdeploy$ python3 -m pip --version
pip 21.2.4 from /mnt/d/khj/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
(base) khj@khj:~/mmdeploy$ pip --version
pip 22.0.4 from /mnt/d/khj/.local/lib/python3.8/site-packages/pip (python 3.8)
```

## Modification

Use `python3 -m pip install` instead of `pip install`

## BC-breaking (Optional)

no BC-breaking.

## Use cases (Optional)

no need test case.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]
LGTM

**Review by AllentDan — COMMENTED** [review]
Just out of curiosity, users may know which pip through `which pip`?
BTW, `python3 -m pip` does not work under my Windows system.
```cmd
(pytorch) PS C:\Users\Administrator> python3 -m pip install six
(pytorch) PS C:\Users\Administrator> pip install six
Requirement already satisfied: six in c:\programdata\anaconda3\envs\pytorch\lib\site-packages (1.15.0)
```

**Comment by lvhan028** [comment]
Since mmdeploy creates a conda env as suggested in the document, why there are more than 2 versions of python?

**Comment by tpoisonooo** [comment]
> Since mmdeploy creates a conda env as suggested in the document, why there are two versions of python?

WSL2 (ubuntu 20.04) gives  python3.8 and pip by default.

**Comment by tpoisonooo** [comment]
> 

In my laptop (win11),  `python` would trigger `Microsoft Store`, guide me to install Python3.10

```Bash
C:\Users\khjap>python3 -m ensurepip

C:\Users\khjap>python3 --help

C:\Users\khjap>python3
```

After installation, it works fine.

```Bash
C:\Users\khjap>python3 --version
Python 3.10.4

C:\Users\khjap>python3 -m pip --version
pip 22.0.4 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\site-packages\pip (python 3.10)

C:\Users\khjap>pip --version
pip 22.0.4 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\site-packages\pip (python 3.10)
```

**Comment by AllentDan** [comment]
> ```shell
> python3 
> ```

In this regard, `python3 -m pip` may not be the best way for users to use. How about adding the description to FAQs?

**Comment by tpoisonooo** [comment]
> > ```shell
> > python3 
> > ```
> 
> In this regard, `python3 -m pip` may not be the best way for users to use. How about adding the description to FAQs?

OK, added to FAQ.md, close PR.

check https://github.com/open-mmlab/mmdeploy/pull/352

**Pull request closed without merging**
