### PR TITLE
Roman duris/fix jetson wheel platform

### PR DESCRIPTION
**Pull request by roman-duris**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fixes open-mmlab/mmdeploy#2493

## Modification

in generate_build_config.py in package_tools change "wheel platform tag" to <any> for "system flag" <jetson>

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by RunningLeon** [comment]
@roman-duris Hi, thanks for your PR. Could you sign the [cla](https://cla-assistant.io/open-mmlab/mmdeploy?pullRequest=2497).

**Comment by roman-duris** [comment]
Sorry for the late response and reaction. I had to get approval for CLA, now everything shoub de ready for merge @RunningLeon.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by JNaranjo-Alcazar** [comment]
Hi,
I would like to install mmdeploy_runtime on a Jetson Orin. Following a little bit the issues in the repo I have arrived here where it seems that a modification is made so that it can be installed.
However, it is not clear to me how to do it.
Is there any tutorial or can you give me some help to get it?

Thanks in advance

**Pull request merged**
