### PR TITLE
[Bug] compatible with torch 1.11

### PR DESCRIPTION
**Pull request by AllentDan**
Use `verbose` instead of `strip_doc_string` for onnx export according to [official docstring](https://pytorch.org/docs/master/onnx.html#functions)

Related issue #268.

### CODE REVIEW

**Comment by grimoire** [comment]
I can't find any description about `strip_doc_string` in the official link you provided.

**Comment by AllentDan** [comment]
> I can't find any description about `strip_doc_string` in the official link you provided.

Yes, but it is used in our codebase. It is deprecated in the latest pytorch.

**Comment by AllentDan** [comment]
> verbose

Given by the userwarning of pytorch:
```
UserWarning: strip_doc_string' is deprecated and ignored. Will be removed in next PyTorch release. It's combined with verbose' argument now. warnings.warn("strip_doc_string' is deprecated and ignored. Will be removed in "
```

**Comment by grimoire** [comment]
Do we really need this doc_string? Can we simply remove it? Verbose is really annoy.

**Comment by AllentDan** [comment]
Well, that makes no difference to me acutally. But we may ask @SemyonBevzuk for the reason adding it and detemine then.

**Comment by SemyonBevzuk** [comment]
Previously, `strip_doc_string` could be useful for determining which string in Python code is associated with a graph node in ONNX.
This can be quite useful when debugging export-related errors. So it seems to me that this functionality needs to be supported.

**Review by grimoire — APPROVED** [review]

**Review by SemyonBevzuk — APPROVED** [review]

**Pull request merged**
