### PR TITLE
[Fix] Fix reppoints TensorRT support.

### PR DESCRIPTION
**Pull request by grimoire**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Reppoint give wrong result on latest TensorRT.

## Modification

Reshape twice.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by hanrui1sensetime — COMMENTED** [review]
In my env: 
torch 1.10.0 + cu113
tensorrt 8.4.2.4
This conversion will failed on onnx2tensorrt.
```
[TRT] [W] Skipping tactic 0x0000000000000000 due to Myelin error: autotuning: CUDA error 3 allocating 0-byte buffer: 
[09/27/2022-11:10:30] [TRT] [E] 4: [optimizer.cpp::computeCosts::3624] Error Code 4: Internal Error (Could not find any implementation for node {ForeignNode[Transpose_600 + Reshape_603...Gather_1063]} due to insufficient workspace. See verbose log for requested sizes.)
```

**Review by hanrui1sensetime — COMMENTED** [review]
And in another env:
tensorrt 8.0.3.4
pytorch 1.8.0+cuda102:
It fails at:
```
RuntimeError: Failed to parse onnx, In node 1061 (importClip): UNSUPPORTED_NODE: Assertion failed: inputs.at(2).is_weights() && "Clip max value must be an initializer!"
```

**Comment by hanrui1sensetime** [comment]
LGTM. 
P.S. The same as CenterNet, in trt 8.4.x, dynamic shape will get wrong answer. https://github.com/NVIDIA/TensorRT/issues/2299

**Review by hanrui1sensetime — APPROVED** [review]

**Review by tpoisonooo — APPROVED** [review]
LGTM.

**Pull request merged**
