### PR TITLE
[Fix] fix ncnn torch 1.12 master

### PR DESCRIPTION
**Pull request by hanrui1sensetime**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

In torch 1.12, some constant initializer which uses in multiple places will generate `Identity` ops in onnx, which will failed in ncnn.
So we fix the fuse pass in the onnx2ncnn to remove these `Identity` nodes.

## Modification

Fuse_pass.cpp and onnx2ncnn.cpp

## BC-breaking (Optional)

None.

## Use cases (Optional)

In torch1.12 ncnn deployment which failed before. A typical example are models which have some `Resize` ops which reuse `scale` initializers.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by tpoisonooo — APPROVED** [review]
LGTM after  https://github.com/open-mmlab/mmdeploy/pull/1431 merged.

**Comment by grimoire** [comment]
Why do we write a pass? we can just map Identity to Noop

**Comment by hanrui1sensetime** [comment]
> Why do we write a pass? we can just map Identity to Noop

Noop requires one bottomtop blob, while Identity requires one bottom blob and one top blob. If we map Identity to Noop, we still need substitute the Identity output node to Identity input node for nodes which using Identity's output as input. This step is the same as the fuse_identity function.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
