### PR TITLE
Add Core ML common configuration

### PR DESCRIPTION
**Pull request by Typiqally**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Allow users to be able to change parameters that are used to invoke coremltools, such as compute precision and deployment target. The PR came forward from issue #1242.

## Modification

Make (almost) all parameters for coremltools conversion function configurable in https://github.com/Typiqally/mmdeploy/blob/4da04fff3aff3c1e2d9d71253ad8c37848670c50/configs/_base_/backends/coreml.py#L4-L8. Inspired from existing tensorrt deployment: https://github.com/open-mmlab/mmdeploy/blob/d8e6229dc51ed84ca10a54926d245a1007903183/tools/deploy.py#L196-L226

Additionally, added missing default config files for mmdetection instance segmentation models.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by irexyc — APPROVED** [review]
HI Typiqally, thanks for your pull request, it looks greate to me.

**Comment by lvhan028** [comment]
Please resolve the linting error. 
May merge master to fix `ci/circleci: test_windows_onnxruntime`

**Comment by Typiqally** [comment]
> Please resolve the linting error. May merge master to fix `ci/circleci: test_windows_onnxruntime`

Linting issues should be fixed since latest commit. I don't think `ci/circleci: test_windows_onnxruntime` is an issue as a result of this PR.

**Comment by irexyc** [comment]
> Please resolve the linting error. May merge master to fix `ci/circleci: test_windows_onnxruntime`

The issue is introduced by pr1183, and will be fixed by pr1309

**Comment by Typiqally** [comment]
Alright, is there anything left to fix before this PR can be approved?

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
