### PR TITLE
[Enhancement] Fix tests for OpenVINO with Python 3.6

### PR DESCRIPTION
**Pull request by SemyonBevzuk**
## Motivation
Fixed problem #118 with `capture_output` when using Python 3.6.

## Modification
- `docs/en/tutorials/how_to_support_new_backends.md`: Updated documentation.
- `mmdeploy/backend/openvino/onnx2openvino.py`: Replaced `capture_output` with `stdout=PIPE, stderr=PIPE`.

### CODE REVIEW

**Comment by SemyonBevzuk** [comment]
```python
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcls/models/backbones/twins.py:9: in <module>
    from mmcv.cnn.bricks.transformer import FFN, PatchEmbed
E   ImportError: cannot import name 'PatchEmbed' from 'mmcv.cnn.bricks.transformer' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)
```
It seems that `PatchEmbed` was first used in MMCV [v1.4.1](https://github.com/open-mmlab/mmcv/blob/f31f1cdb8ee6671a512d6756d2f0dfd68d04272f/mmcv/cnn/bricks/transformer.py#L152). Maybe it should be updated?

**Comment by RunningLeon** [comment]
> ```python
> /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcls/models/backbones/twins.py:9: in <module>
>     from mmcv.cnn.bricks.transformer import FFN, PatchEmbed
> E   ImportError: cannot import name 'PatchEmbed' from 'mmcv.cnn.bricks.transformer' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)
> ```
> 
> It seems that `PatchEmbed` was first used in MMCV [v1.4.1](https://github.com/open-mmlab/mmcv/blob/f31f1cdb8ee6671a512d6756d2f0dfd68d04272f/mmcv/cnn/bricks/transformer.py#L152). Maybe it should be updated?



> ```python
> /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcls/models/backbones/twins.py:9: in <module>
>     from mmcv.cnn.bricks.transformer import FFN, PatchEmbed
> E   ImportError: cannot import name 'PatchEmbed' from 'mmcv.cnn.bricks.transformer' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)
> ```
> 
> It seems that `PatchEmbed` was first used in MMCV [v1.4.1](https://github.com/open-mmlab/mmcv/blob/f31f1cdb8ee6671a512d6756d2f0dfd68d04272f/mmcv/cnn/bricks/transformer.py#L152). Maybe it should be updated?

@SemyonBevzuk Thanks.
@mzr1996, hi coud you take a look at this? Did not see that mmcls==0.20.0 has dependency of mmcv > 1.4.0 in [requirements](https://github.com/open-mmlab/mmclassification/tree/8e4a496f9c8e58c9440a5a6578257c68fd7f2029/requirements)

**Comment by mzr1996** [comment]
We have fixed it in mmcls v0.20.1, and the mmcv dependency is updated to v1.4.2

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by RunningLeon** [comment]
@SingleZombie Could you review this PR?

**Review by SingleZombie — APPROVED** [review]
LGTM

**Pull request merged**
