### PR TITLE
[Doc] update SAR status

### PR DESCRIPTION
**Pull request by AllentDan**
Fixed SAR exporting for TorchScript. Updated the status of SAR.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]
LGTM

**Comment by RunningLeon** [comment]
@AllentDan Could you rebase to `main` branch? CI error is fixed on `main` branch.

**Comment by RunningLeon** [comment]
could fix ci errors

**Comment by RunningLeon** [comment]
@AllentDan Could sync with latest main branch.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
