### PR TITLE
Upgrade Dockerfile to use TensorRT==8.2.4.2

### PR DESCRIPTION
**Pull request by nijkah**
## Motivation
Currently, many documents seem to suppose that the user installed TRT >= 8.*.
But, Dockerfile does not follow it, therefore related issues happen when using a given Dockerfile.

## Modification
- Upgrade the base image to use TensorRT 8.2.4.2. See [release note](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_22-04.html#rel_22-04).
  - Fix wrong environment variable for `LD_LIBRARY_PATH` (the image does not include `/usr/local/cuda-11.3/`).
- Upgrade torch & torchvision
- Upgrade MMCV

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
Hi, @nijkah 
Thanks for your PR. 
MMDeploy can support TensorRT with different versions.
So I think it benefits users if we create another docker file to bring in TensorRT 8.2.4.2, for example `Dockerfile-tensorrt-22.04`.
In this way, users can build the docker image as follows,

```shell
cd mmdeploy
docker build -f docker/GPU/Dockerfile-tensorrt-22.04 .
```

**Comment by AllentDan** [comment]
Hi, @nijkah. Thanks for your kindly pulling request to MMDeploy. However, the base image of Dockerfile is actually optional for users. It is not a big deal for users to modify the file to their preference. After setting the version of the base image, users can choose the versions of the torch, mmcv through:
```
docker build docker/ -t mmdeploy:master-gpu --build-arg  TORCH_VERSION=1.10.0 MMCV_VERSION=1.5.3
```

**Comment by nijkah** [comment]
Hi, @lvhan028 @AllentDan. I understand this PR seems not necessary.
I just want to point out that the motivation of this PR was that some operators are not converted with TensorRT==7.*.
I found this happens in [`oriented-rcnn`](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmrotate.md).

It will be better to specify the supported version of TensorRT in each model!
Is there any good idea?

**Comment by AllentDan** [comment]
> Hi, @lvhan028 @AllentDan. I understand this PR seems not necessary. I just want to point out that the motivation of this PR was that some operators are not converted with TensorRT==7.*. I found this happens in [`oriented-rcnn`](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmrotate.md) when converting it to TensorRT-dynamic.
> 
> It will be better to specify the supported version of TensorRT in each model! Is there any good idea?

I see. TensorRT 7 might not be supported in the future as TensorRT is updating fast. In this aspect, this PR is actually necessary.

**Review by AllentDan — COMMENTED** [review]
If you don't mind, please update the package versions of the CPU Dockerfile.

**Review by AllentDan — APPROVED** [review]
LGTM

**Comment by nijkah** [comment]
In addition to this, should I add installing pycuda or is it optional?
Although users can install it, it will make your Dockerfile ready for use.

**Comment by AllentDan** [comment]
> In addition to this, should I add installing pycuda or is it optional? Although users can install it, it will make the Dockerfile ready for use.

There are users already complaining about docker image size. May leave it to users' preferences.

**Comment by vansprosk8** [comment]
Current Docker file can convert detector yolox into trt engine, but mmdeploy with fresh TensorRT >8 crashed when converting to trt engine. We really need tested new Docker. https://github.com/open-mmlab/mmdeploy/issues/460

**Comment by nijkah** [comment]
> Current Docker file can convert detector yolox into trt engine, but mmdeploy with fresh TensorRT >8 crashed when converting to trt engine. We really need tested new Docker. #460

Hi @vansprosk8, thank you for reporting the issue. I'll check yolox case.
Can I kindly ask you to provide the exact configuration file tested?

**Comment by nijkah** [comment]
I checked the error reproduces in the command.
```
python3 tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py ../mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py ../mmdetection/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth ../mmdetection/demo/demo.jpg --device cuda
```
Error raises in the exact same node `Concat_351: dimensions not compatible for concatenation)`.

**Comment by AllentDan** [comment]
> I checked the error reproduces in the command.
> 
> ```
> python3 tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py ../mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py ../mmdetection/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth ../mmdetection/demo/demo.jpg --device cuda
> ```
> 
> The error raises in the exact same node `Concat_351: dimensions not compatible for concatenation`.

Is is possible that the error was raised by TensorRT as the dynamic shape inference always triggers bugs in my experience. Maybe we have toe find out a new version of TensorRT docker image that works fine for all the models.

**Comment by AllentDan** [comment]
Hi, @nijkah. If you don't mind, could you help remove `-p` for the [doc](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/build_from_docker.md#run-docker-container) as there are confusions like the issue [here](https://github.com/open-mmlab/mmdeploy/issues/712)

**Comment by lvhan028** [comment]
> Current Docker file can convert detector yolox into trt engine, but mmdeploy with fresh TensorRT >8 crashed when converting to trt engine. We really need tested new Docker. #460

Totally agreed. We are working on it.
I am afraid it will take quite some time. So this PR probably will be held on for quite a while. 
Hope you can understand it,  @nijkah.

**Comment by lvhan028** [comment]
By running `python tools/regression_test.py --codebase mmdet --backend tensorrt sdk --performance`, I found `yolov3` and `yolox` failed.
The `yolov3` failure is because the `input_shape` in tensorrt deployment config is incorrect. 
using below config can resolve the issue.
```python
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 64, 64],
                    opt_shape=[1, 3, 320, 320],
                    max_shape=[1, 3, 608, 608])))
    ])
```
As for `yolox`, after preprocessing, the image shape is fixed to [640 x 640]. If we use static shape config, the deployment can be successful. But if I change it to dynamic shape, an error happened, showing `[TRT] [E] 4: [graphShapeAnalyzer.cpp::processCheck::581] Error Code 4: Internal Error (Concat_351: dimensions not compatible for concatenation)`

@AllentDan could you help investigate it?

**Comment by AllentDan** [comment]
Hi, @nijkah. I've fixed the bug of YOLOX exporting to TensorRT in PR #758. Could you test if it works fine for your PR? If it is OK, we can merge the two PRs both.

**Comment by nijkah** [comment]
Hi @lvhan028, should I add a file like `configs/mmdet/_base_/base_tensorrt_dynamic-64x64-608x608.py ` to support yolov3 models?

**Comment by nijkah** [comment]
@AllentDan I tested it, and it works fine! 🚀

**Comment by lvhan028** [comment]
> Hi @lvhan028, should I add a file like `configs/mmdet/_base_/base_tensorrt_dynamic-64x64-608x608.py` to support yolov3 models?

Let us do a team discussion. I'll get back to you asap.

**Comment by lvhan028** [comment]
Hi, @nijkah let's change `160x160-608x608` to `64x64-608x608`

**Comment by nijkah** [comment]
> Hi, @nijkah let's change `160x160-608x608` to `64x64-608x608`

The Files need to be updated are `detection_tensorrt-fp16_dynamic-160x160-608x608.py`, `detection_tensorrt-int8_dynamic-160x160-608x608.py`, `detection_tensorrt_dynamic-160x160-608x608.py` in `mmdeploy/configs/mmdet/detection/`.
Right?

**Comment by lvhan028** [comment]
> 

Yes. And `YOLOV3` config in `mmdet.yml` should also be updated:
```YAML
models:
  - name: YOLOV3
    metafile: configs/yolo/metafile.yml
    model_configs:
      - configs/yolo/yolov3_d53_320_273e_coco.py
    pipelines:
      - *pipeline_ts_fp32
      - *pipeline_ort_dynamic_fp32
      - deploy_config: configs/mmdet/detection/detection_tensorrt-fp16_dynamic-64x64-608x608.py
        convert_image: *convert_image
        backend_test: *default_backend_test
        sdk_config: *sdk_dynamic
#      - *pipeline_trt_dynamic_fp32
#      - *pipeline_trt_dynamic_fp16
#      - *pipeline_trt_dynamic_int8
      - *pipeline_ncnn_static_fp32
#      - *pipeline_pplnn_dynamic_fp32
      - *pipeline_openvino_dynamic_fp32

```

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
