### PR TITLE
[Docs] Minor fixes and translation of installation tutorial for Jetson

### PR DESCRIPTION
**Pull request by Dchaoqun**
## Motivation

Support to improve the English version of [how_to_install_mmdeploy_on_jetsons](https://github.com/open-mmlab/mmdeploy/blob/8e6d4defc6946aa7778d556ea51ad05dafbbde31/docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md) and translate it into Chinese.

## Modification

- Correction of grammar mistakes.
- Translation to Chinese.

### CODE REVIEW

**Review by AllentDan — COMMENTED** [review]
After PR #381

**Comment by lvhan028** [comment]
Hi, @Dchaoqun, PR #381 has changed the `docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md`. Could you please update your PR based on the latest master?

**Comment by Dchaoqun** [comment]
> Hi, @Dchaoqun, PR #381 has changed the `docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md`. Could you please update your PR based on the latest master?

Sure. Will do this week.

**Comment by Dchaoqun** [comment]
> Hi, @Dchaoqun, PR #381 has changed the `docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md`. Could you please update your PR based on the latest master?

Hi @lvhan028 , the updates are done.

**Review by lvhan028 — APPROVED** [review]
LGTM

**Review by AllentDan — APPROVED** [review]
LGTM

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @Dchaoqun ！First of all, we want to express our gratitude for your significant PR in the mmdeploy project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
