### PR TITLE
Support windows tensorrt backend.

### PR DESCRIPTION
**Pull request by ypwhs**
# Environment

```
2022-01-26 17:46:08,338 - mmdeploy - INFO - **********Environmental information**********
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2022-01-26 17:46:09,600 - mmdeploy - INFO - sys.platform: win32
2022-01-26 17:46:09,600 - mmdeploy - INFO - Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
2022-01-26 17:46:09,600 - mmdeploy - INFO - CUDA available: True
2022-01-26 17:46:09,600 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
2022-01-26 17:46:09,600 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2022-01-26 17:46:09,600 - mmdeploy - INFO - NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
2022-01-26 17:46:09,600 - mmdeploy - INFO - GCC: n/a
2022-01-26 17:46:09,600 - mmdeploy - INFO - PyTorch: 1.10.0+cu113
2022-01-26 17:46:09,600 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2022-01-26 17:46:09,600 - mmdeploy - INFO - TorchVision: 0.11.1+cu113
2022-01-26 17:46:09,600 - mmdeploy - INFO - OpenCV: 4.5.2
2022-01-26 17:46:09,600 - mmdeploy - INFO - MMCV: 1.4.2
2022-01-26 17:46:09,600 - mmdeploy - INFO - MMCV Compiler: MSVC 192930136
2022-01-26 17:46:09,600 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-01-26 17:46:09,600 - mmdeploy - INFO - MMDeployment: 0.1.0+d522874
2022-01-26 17:46:09,600 - mmdeploy - INFO -

2022-01-26 17:46:09,601 - mmdeploy - INFO - **********Backend information**********
2022-01-26 17:46:09,882 - mmdeploy - INFO - onnxruntime: None ops_is_avaliable : False
2022-01-26 17:46:09,882 - mmdeploy - INFO - tensorrt: 8.2.1.8 ops_is_avaliable : True
2022-01-26 17:46:09,884 - mmdeploy - INFO - ncnn: None ops_is_avaliable : False
2022-01-26 17:46:09,884 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-01-26 17:46:09,885 - mmdeploy - INFO - openvino_is_avaliable: False
2022-01-26 17:46:09,885 - mmdeploy - INFO -

2022-01-26 17:46:09,885 - mmdeploy - INFO - **********Codebase information**********
2022-01-26 17:46:09,885 - mmdeploy - INFO - mmcls: None
2022-01-26 17:46:09,886 - mmdeploy - INFO - mmdet: 2.20.0
2022-01-26 17:46:09,886 - mmdeploy - INFO - mmedit: None
2022-01-26 17:46:09,887 - mmdeploy - INFO - mmocr: None
2022-01-26 17:46:09,887 - mmdeploy - INFO - mmseg: None

```

# Reason

Windows build .dll file:

image

So load_plugin need to check platform for windows.

# Result

Test result:

企业微信截图_1643190031842

Successfully loaded mmdeploy_tensorrt_ops.dll.

### CODE REVIEW

**Comment by lvhan028** [comment]
Thanks so much for supporting the Windows platform. 
In PR #106, we are trying to make MMDeploy the whole package working on the Windows platform
Would you like to work together and make your PR to https://github.com/lzhangzz/mmdeploy? @lzhangzz can add permission.

**Comment by RunningLeon** [comment]
@ypwhs Hi, thanks for your PR. @lzhangzz, @SingleZombie, could you guys take a look at this PR?

**Comment by SingleZombie** [comment]
@ypwhs Hi! Could you provide your cmake command to compile the library on Windows so that we can update our documents.

**Comment by ypwhs** [comment]
> @ypwhs Hi! Could you provide your cmake command to compile the library on Windows so that we can update our documents.

Sure.

```
cmake .. \
-DTENSORRT_DIR=C:/Users/admin/Desktop/tensorrt/TensorRT-8.2.1.8 \
-DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
-DMMDEPLOY_TARGET_BACKENDS=trt
cmake --build . --config Release -j
cmake --install .
```

Note:

* `-DCUDNN_DIR` is not working on Windows, you need to put cudnn files in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3`.
* `CMAKE_CUDA_STANDARD` need change to 17, https://github.com/open-mmlab/mmdeploy/blob/v0.2.0/cmake/cuda.cmake#L56

**Review by SingleZombie — APPROVED** [review]
LGTM

**Comment by RunningLeon** [comment]
@lzhangzz Hi, Any comment on this PR?

**Comment by lzhangzz** [comment]
This is OK for now.

However, in the Windows PR #106, DLLs are moved to `build\bin`.

**Comment by ypwhs** [comment]
> This is OK for now.
> 
> However, in the Windows PR #106, DLLs are moved to `build\bin`.

Thanks for your work, you do better.

**Comment by lvhan028** [comment]
PR #106 address windows build issues both for custom ops and SDK

**Pull request closed without merging**
