### PR TITLE
[Fix] Fix dbnet regression test

### PR DESCRIPTION
**Pull request by AllentDan**
Directly set pytorch metric when it's empty for regression_test.py.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]

**Comment by AllentDan** [comment]
@RunningLeon Would this change the behavior of MMDet? I heard that the MMDet coco dataset stuff is sensitive to multiple datasets settings.

**Comment by RunningLeon** [comment]
> @RunningLeon Would this change the behavior of MMDet? I heard that the MMDet coco dataset stuff is sensitive to multiple datasets settings.

Not sure, maybe you could start a fast test with jenkins.

**Comment by AllentDan** [comment]
> > @RunningLeon Would this change the behavior of MMDet? I heard that the MMDet coco dataset stuff is sensitive to multiple datasets settings.
> 
> Not sure, maybe you could start a fast test with jenkins.

Tested OK with 1660 card.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
