### PR TITLE
[Enhancement] Support RTMDet-Ins

### LINKED ISSUE #1849: [Bug] RTMDet-Ins inference with SDK , the result without mask
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**Python:**
image
image

**TIt doesn't exist in C++ either:**
image
image

**This issue is also mentioned in this link:**
https://github.com/open-mmlab/mmdeploy/issues/1722#issue-1573976926 

How to fix it? Thanks!

### Reproduction

Official example:
https://github.com/open-mmlab/mmdetection/tree/3.x/configs/rtmdet 
https://mmdeploy.readthedocs.io/en/1.x/get_started.html#installation

### Environment

```Shell
It seems to have nothing to do with the environment.
```

### Error traceback

_No response_

### PR DESCRIPTION
**Pull request by lzhangzz**
resolves #1849

### CODE REVIEW

**Comment by hanrui1sensetime** [comment]
Seems failed on python demo when the bbox is out of the picture because the `mask` shape and the `mask_img` shape are different.

FYI:
The model you can use rtmdet-ins-tiny-ort.
And the command is
``` shell
python object_detection.py cpu ../../rtmdet-ins-tiny-ort/ ../../../mmdeploy/demo/resources/det.jpg
```
Then the error log is:
```
cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/arithm.cpp:212: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'
```
The cause is:
```
debugging top: 104, top+mask.shape[0]: 141, left: 608, left+mask.shape[1]: 641
debugging mask: (37, 33), mask_img: (37, 32)
```
And the bug is at [here](https://github.com/open-mmlab/mmdeploy/blob/rtmdet-ins-sdk/demo/python/object_detection.py#L40)

**Comment by lvhan028** [comment]
> Seems failed on python demo when the bbox is out of the picture because the `mask` shape and the `mask_img` shape are different.
> 
> FYI: The model you can use rtmdet-ins-tiny-ort. And the command is
> 
> ```shell
> python object_detection.py cpu ../../rtmdet-ins-tiny-ort/ ../../../mmdeploy/demo/resources/det.jpg
> ```
> 
> Then the error log is:
> 
> ```
> cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/arithm.cpp:212: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'
> ```
> 
> The cause is:
> 
> ```
> debugging top: 104, top+mask.shape[0]: 141, left: 608, left+mask.shape[1]: 641
> debugging mask: (37, 33), mask_img: (37, 32)
> ```
> 
> And the bug is at [here](https://github.com/open-mmlab/mmdeploy/blob/rtmdet-ins-sdk/demo/python/object_detection.py#L40)

Can you share the test image?

**Comment by hanrui1sensetime** [comment]
> > Seems failed on python demo when the bbox is out of the picture because the `mask` shape and the `mask_img` shape are different.
> > FYI: The model you can use rtmdet-ins-tiny-ort. And the command is
> > ```shell
> > python object_detection.py cpu ../../rtmdet-ins-tiny-ort/ ../../../mmdeploy/demo/resources/det.jpg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then the error log is:
> > ```
> > cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/arithm.cpp:212: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The cause is:
> > ```
> > debugging top: 104, top+mask.shape[0]: 141, left: 608, left+mask.shape[1]: 641
> > debugging mask: (37, 33), mask_img: (37, 32)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the bug is at [here](https://github.com/open-mmlab/mmdeploy/blob/rtmdet-ins-sdk/demo/python/object_detection.py#L40)
> 
> Can you share the test image?

[det.jpg](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/resources/det.jpg)

**Review by hanrui1sensetime — APPROVED** [review]
LGTM.

**Review by irexyc — APPROVED** [review]

**Comment by lvhan028** [comment]
> > > Seems failed on python demo when the bbox is out of the picture because the `mask` shape and the `mask_img` shape are different.
> > > FYI: The model you can use rtmdet-ins-tiny-ort. And the command is
> > > ```shell
> > > python object_detection.py cpu ../../rtmdet-ins-tiny-ort/ ../../../mmdeploy/demo/resources/det.jpg
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then the error log is:
> > > ```
> > > cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/arithm.cpp:212: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The cause is:
> > > ```
> > > debugging top: 104, top+mask.shape[0]: 141, left: 608, left+mask.shape[1]: 641
> > > debugging mask: (37, 33), mask_img: (37, 32)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And the bug is at [here](https://github.com/open-mmlab/mmdeploy/blob/rtmdet-ins-sdk/demo/python/object_detection.py#L40)
> > 
> > 
> > Can you share the test image?
> 
> [det.jpg](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/resources/det.jpg)

I didn't reproduce it any more

**Review by hanrui1sensetime — APPROVED** [review]

**Comment by roman-duris** [comment]
Hello, I have finally found the problem and luckily also the solution. 
To anyone interested, the problem seems to lie in how Triton copies Inputs and Outpus from video memory to system memory. 
There is something "special" in how RTMDet TensorRT implementation works with video memory and takes heavy performance penalty when mainly outputs have to be copied from video memory to system memory. For example when I tried this with TensorRT conversion of Mask RCNN the performance penalty seems to be much lower. This may be due to the speed of RTMDet and then the IO becomes the bottleneck. 
So the solution is to keep inputs and outputs in CUDA memory during the inference. To verify this I used ```perf_analyzer``` from nvidia triton sdk. 

RTMDET int8 system memory - ```perf_analyzer -m rtmdet_tiny_int8 --verbose```
```
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 76
    Throughput: 4.21814 infer/sec
    Avg latency: 235303 usec (standard deviation 10493 usec)
    p50 latency: 236513 usec
    p90 latency: 248902 usec
    p95 latency: 251810 usec
    p99 latency: 255070 usec
    Avg HTTP time: 226858 usec (send/recv 110490 usec + response wait 116368 usec)
  Server: 
    Inference count: 156
    Execution count: 156
    Successful request count: 156
    Avg request latency: 111585 usec (overhead 51 usec + queue 68 usec + compute input 1810 usec + compute infer 3418 usec + compute output 106237 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 4.21814 infer/sec, latency 235303 usec
```
RTMDet INT8 CUDA MEMORY - ```perf_analyzer -m rtmdet_tiny_int8 --verbose --shared-memory cuda```
```
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 4258
    Throughput: 236.499 infer/sec
    Avg latency: 4226 usec (standard deviation 322 usec)
    p50 latency: 4188 usec
    p90 latency: 4473 usec
    p95 latency: 4788 usec
    p99 latency: 5189 usec
    Avg HTTP time: 4216 usec (send/recv 95 usec + response wait 4121 usec)
  Server: 
    Inference count: 4415
    Execution count: 4415
    Successful request count: 4415
    Avg request latency: 7601 usec (overhead 52 usec + queue 51 usec + compute input 251 usec + compute infer 2920 usec + compute output 4326 usec)
```
Speed Increase of cca 991% -> and CUDA number seems to be much more close to the ones presented in Paper
And for comparison here is Mask RCNN

Mask RCNN system memory - ```perf_analyzer -m maskrcnn_trtint8 --verbose```
```
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 1085
    Throughput: 60.2666 infer/sec
    Avg latency: 16578 usec (standard deviation 1493 usec)
    p50 latency: 16477 usec
    p90 latency: 18505 usec
    p95 latency: 19011 usec
    p99 latency: 20258 usec
    Avg HTTP time: 16563 usec (send/recv 2904 usec + response wait 13659 usec)
  Server: 
    Inference count: 3316
    Execution count: 3316
    Successful request count: 3316
    Avg request latency: 7917 usec (overhead 61 usec + queue 66 usec + compute input 559 usec + compute infer 7169 usec + compute output 61 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 60.2666 infer/sec, latency 16578 usec
```
Mask RCNN CUDA memory - ``` perf_analyzer -m maskrcnn_trtint8 --verbose --shared-memory cuda```
```
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 2230
    Throughput: 123.866 infer/sec
    Avg latency: 8068 usec (standard deviation 536 usec)
    p50 latency: 8036 usec
    p90 latency: 8237 usec
    p95 latency: 8332 usec
    p99 latency: 10514 usec
    Avg HTTP time: 8057 usec (send/recv 99 usec + response wait 7958 usec)
  Server: 
    Inference count: 2230
    Execution count: 2230
    Successful request count: 2230
    Avg request latency: 7606 usec (overhead 57 usec + queue 53 usec + compute input 184 usec + compute infer 7272 usec + compute output 39 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 123.866 infer/sec, latency 8068 usec
```
Speed increase of cca 50%. 

All models have been tested on 1 Titan RTX GPU.

**Pull request merged**
