### PR TITLE
[Fix] fix mmdeploy android library size

### PR DESCRIPTION
**Pull request by irexyc**
## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

- move CMAKE_BUILD_TYPE check before project (otherwise the CMAKE_BUILD_TYPE will be set to RelWithDebInfo)
- add -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False

### CODE REVIEW

**Comment by RunningLeon** [comment]
@irexyc Is it possible to add test workflow for android plantform?

**Comment by lvhan028** [comment]
What's the build size for android platform in this PR?

**Comment by irexyc** [comment]
> What's the build size for android platform in this PR?

40MB

**Comment by lvhan028** [comment]
> > What's the build size for android platform in this PR?
> 
> 40MB

Could you list the size of each module here?

**Review by tpoisonooo — APPROVED** [review]
And I strongly advice to add [opencv-mobile](https://github.com/nihui/opencv-mobile), they removed useless modules and keep cv.core functions.

**Comment by irexyc** [comment]
> Could you list the size of each module here?
```
 11M  libmmdeploy_ncnn_net.so
8.8M  libmmdeploy_mmocr.so // std::getline
6.7M  libmmdeploy_core.so
5.0M  libmmdeploy_opencv_utils.so
1.5M  libmmdeploy_mmpose.so // cv::GaussianBlur
1.4M  libspdlog.a
481K  libmmdeploy_graph.so
411K  libmmdeploy_transform.so
382K  libmmdeploy_mmdet.so
365K  libmmdeploy_executor.so
305K  libmmdeploy_execution.so
289K  libmmdeploy_operation_cpu.so
268K  libmmdeploy_directory_model.so
265K  libmmdeploy_text_recognizer.so
260K  libmmdeploy_pose_tracker.so
248K  libmmdeploy_mmseg.so
246K  libmmdeploy_text_detector.so
244K  libmmdeploy_net_module.so
238K  libmmdeploy_mmaction.so
228K  libmmdeploy_java.so
224K  libmmdeploy_mmcls.so
199K  libmmdeploy_mmrotate.so
183K  libmmdeploy_mmedit.so
167K  libmmdeploy_transform_module.so
158K  libmmdeploy_dlpack_utils.a
155K  libmmdeploy_pose_detector.so
155K  libmmdeploy_detector.so
154K  libmmdeploy_common.so
153K  libmmdeploy_video_recognizer.so
146K  libmmdeploy_pipeline.so
145K  libmmdeploy_segmentor.so
144K  libmmdeploy_rotated_detector.so
142K  libmmdeploy_classifier.so
139K  libmmdeploy_operation.so
139K  libmmdeploy_restorer.so
130K  libmmdeploy_model.so
128K  libmmdeploy_operation_dummy.so
111K  libmmdeploy_cpu_device.so
```

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
