### PR TITLE
fix pytorch deepcopy trace error

### PR DESCRIPTION
**Pull request by AllentDan**
#1727 
#2203 
#2318

### CODE REVIEW

**Review by grimoire — APPROVED** [review]

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by BooHwang** [comment]
however it still exists bug when convert mask2former to onnx.

**Comment by RunningLeon** [comment]
> however it still exists bug when convert mask2former to onnx.
@BooHwang 

hi, pls. create an issue and provide mmdeploy env info to reproduce by running `tools/check_env.py`

**Comment by mike-qd** [comment]
I'm also encountering problem when convert mask2former to onnx: 
image
Here is my command and env info: 
python  mmdeploy/tools/deploy.py \
        mmdeploy/configs/mmseg/segmentation_onnxruntime_dynamic.py \
        mmsegmentation/configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py \
        mmsegmentation/ckpt/mask2former_r50_8xb2-160k_ade20k-512x512_20221204_000055-2d1f55f1.pth \
        mmsegmentation/demo/demo.png \
        --work-dir ./ \
        --device cuda \
        --dump-info
[mmdeploy_env.txt](https://github.com/user-attachments/files/21708762/mmdeploy_env.txt)

**Comment by xzh929** [comment]
> I'm also encountering problem when convert mask2former to onnx: image Here is my command and env info: python mmdeploy/tools/deploy.py mmdeploy/configs/mmseg/segmentation_onnxruntime_dynamic.py mmsegmentation/configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py mmsegmentation/ckpt/mask2former_r50_8xb2-160k_ade20k-512x512_20221204_000055-2d1f55f1.pth mmsegmentation/demo/demo.png --work-dir ./ --device cuda --dump-info [mmdeploy_env.txt](https://github.com/user-attachments/files/21708762/mmdeploy_env.txt)

hello,I also have this problem, have you solved it?In my case, I convert mask2former to trt, but the result is different from using pth files with mmseg demo, I think it's the reason of dynamic images input.

**Comment by zaqai** [comment]
> > I'm also encountering problem when convert mask2former to onnx: image Here is my command and env info: python mmdeploy/tools/deploy.py mmdeploy/configs/mmseg/segmentation_onnxruntime_dynamic.py mmsegmentation/configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py mmsegmentation/ckpt/mask2former_r50_8xb2-160k_ade20k-512x512_20221204_000055-2d1f55f1.pth mmsegmentation/demo/demo.png --work-dir ./ --device cuda --dump-info [mmdeploy_env.txt](https://github.com/user-attachments/files/21708762/mmdeploy_env.txt)
> 
> hello,I also have this problem, have you solved it?In my case, I convert mask2former to trt, but the result is different from using pth files with mmseg demo, I think it's the reason of dynamic images input.

did you solve this problem? I also convert mask2former to trt. I got an error. I used the official config and official pth.
`RuntimeError: NYI: Named tensors are not supported with the tracer`

**Pull request merged**
