### PR TITLE
feat(CI): add rust-mmdeploy

### PR DESCRIPTION
**Pull request by liu-mengyang**
## Motivation

Integrate Rust API by linking to [rust-mmdeploy](https://github.com/liu-mengyang/rust-mmdeploy), which is a work from summer camp of MMDeploy. Enable mmdeploy for rustaceans officially.

## Modification

- Write a yaml file `rust_api.yml` to add testing of rust-mmdeploy in CI of mmdeploy.

## Checklist

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
- [x] If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by tpoisonooo** [comment]
How to fix lint:
```bash
$ python3 -m pip install pre-commit
$ pre-commit install .
$ pre-commit run --all-files
```

**Comment by tpoisonooo** [comment]
How to debug CI:

https://github.com/csexton/debugger-action

**Comment by liu-mengyang** [comment]
Development is completed.

**Review by tpoisonooo — APPROVED** [review]
LGTM.

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
