### PR TITLE
[Fix] Fix the warning method that calls the trt logger

### PR DESCRIPTION
**Pull request by Joyphy**
## Motivation
logger.warning failed during trt conversion

## Modification
use mmdeploy logger

### CODE REVIEW

**Comment by lvhan028** [comment]
Hi, @Joyphy 
A similar issue has been fixed in master branch: https://github.com/open-mmlab/mmdeploy/pull/1755

I think it's better to use `get_root_logger()` to log the warnings and leave the `logger` for tensorrt internal log

**Comment by Joyphy** [comment]
OK, I modified it the same way as #1755.

**Review by lvhan028 — APPROVED** [review]

**Review by AllentDan — APPROVED** [review]
LGTM

**Comment by jason102811** [comment]
Hi @Joyphy ！First of all, we want to express our gratitude for your significant PR in the MMDeploy . Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
