### PR TITLE
Added the ability to build a project with PyTorch 2.0.

### PR DESCRIPTION
**Pull request by Danil328**
## Motivation

I use mmdeploy in my project.

## Modification

Added the ability to build a project with PyTorch 2.0.
Namely, I added the flag -std=c++17 to extra_compile_args in setup.py depending on the version of Torch like mmcv setup.py.
https://github.com/open-mmlab/mmcv/blob/main/setup.py#L203

### CODE REVIEW

**Comment by RunningLeon** [comment]
> [CLA assistant check](https://cla-assistant.io/open-mmlab/mmdeploy?pullRequest=2553) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmdeploy?pullRequest=2553) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmdeploy?pullRequest=2553) it.

hi, thanks for your PR. Could you sign the cla? 
Best regards.

**Comment by irexyc** [comment]
You forget to import `parse_version`. 
May fix it and check if the ci could pass.

**Comment by Danil328** [comment]
> You forget to import `parse_version`. May fix it and check if the ci could pass.

Thank you very much, import added.

**Review by irexyc — APPROVED** [review]

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
