### PR TITLE
[Fix] Sync codebase 2.0

### PR DESCRIPTION
**Pull request by hanrui1sensetime**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

After codebase 2.0 releases, some of mmcls and mmdet deployment failed. 

Attention: mmcls sdk still has problems because ResizeEdge is not implemented in SDK. 

## Modification
- [x] Fix mmdet features
- [x] Fix mmdet ut
- [x] Fix mmdet SDK(python and cpp)
- [x] Fix mmcls features
- [x] Fix mmcls UT
- [x] Fix mmcls SDK 

## BC-breaking (Optional)

None.

## Use cases (Optional)

None.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by RunningLeon** [comment]
@hanrui1sensetime some tests failed
```
================================================================== short test summary info ===================================================================
FAILED tests/test_codebase/test_mmcls/test_classification.py::test_build_pytorch_model[False] - KeyError: 'ImageClassifier is not in the model registry. Pl...
FAILED tests/test_codebase/test_mmcls/test_classification.py::test_create_input - KeyError: 'ResizeEdge is not in the transform registry. Please check whet...
FAILED tests/test_codebase/test_mmcls/test_classification.py::test_visualize - KeyError: 'ResizeEdge is not in the transform registry. Please check whether...
FAILED tests/test_codebase/test_mmcls/test_classification.py::test_build_dataset_and_dataloader - KeyError: 'ImageNet is not in the dataset registry. Pleas...
FAILED tests/test_codebase/test_mmcls/test_classification.py::test_build_test_runner - KeyError: 'ImageNet is not in the dataset registry. Please check whe...
FAILED tests/test_codebase/test_mmcls/test_mmcls_models.py::test_vision_transformer_backbone__forward[Backend.NCNN] - KeyError: 'VisionTransformer is not i...
FAILED tests/test_codebase/test_mmdet/test_object_detection.py::test_build_test_runner - FileNotFoundError: Caught FileNotFoundError in DataLoader worker p...
============================================= 7 failed, 87 passed, 2 skipped, 387 warnings in 214.88s (0:03:34) ==============================================
```

**Comment by RunningLeon** [comment]
@hanrui1sensetime failed on torchscript for mmcls:
```
Traceback (most recent call last):
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/pytorch2torchscript.py", line 54, in torch2torchscript
    trace(
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/torch_jit/trace.py", line 96, in trace
    else func(inputs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmcls/models/classifiers/base.py", line 33, in base_classifier__forward
    feats = self.extract_feat(batch_inputs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/mmcls/models/classifiers/image.py", line 192, in extract_feat
    x = self.backbone(inputs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/mmcls/models/backbones/vision_transformer.py", line 510, in forward
    x, patch_resolution = self.patch_embed(x)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 269, in forward
    x = self.projection(x)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/envs/torch1.10.0/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
09/09 02:28:23 - mmengine - ERROR - /root/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2torchscript.torch2torchscript` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
failed on tensorrt + sdk
```
Traceback (most recent call last):
  File "./tools/deploy.py", line 396, in <module>
    main()
  File "./tools/deploy.py", line 125, in main
    export2SDK(deploy_cfg, model_cfg, args.work_dir, pth=checkpoint_path)
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 387, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir=work_dir)
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 324, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg)
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 224, in get_preprocess
    transforms['type'] = 'Resize'
TypeError: list indices must be integers or slices, not str
```

**Comment by hanrui1sensetime** [comment]
Done.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Review by AllentDan — APPROVED** [review]

**Comment by WuChannn** [comment]
I can still meet the similar problem when i convert .pth model to onnx: AttributeError: module 'mmcv' has no attribute 'Config'. it's obviously that mmcv version is not match with mmdeploy. could you show the worked mmcv and mmdeploy version?

my versions are:
mmcv                    2.0.0rc1 
mmdeploy                0.10.0   dev-1.x
mmdet                   3.0.0rc2
mmengine                0.2.0
mmocr                   1.0.0rc2 dev-1.x

**Comment by RunningLeon** [comment]
> @hanrui1sensetime @RunningLeon @AllentDan @lvhan028 I can still meet the similar problem when i convert .pth model to onnx: AttributeError: module 'mmcv' has no attribute 'Config'. it's obviously that mmcv version is not match with mmdeploy. could you show the worked mmcv and mmdeploy version?
> 
> my versions are: mmcv 2.0.0rc1 mmdeploy 0.10.0 dev-1.x(branch) mmdet 3.0.0rc2 mmengine 0.2.0 mmocr 1.0.0rc2 1.x(branch)

@WuChannn Hi, could you create an issue and give info such as env by running `python tools/check_env.py`?

**Comment by WuChannn** [comment]
@RunningLeon thanks for your instant reply. I can't run ```python tools/check_env.py?``, for it raises the same problem:

Screen Shot 2022-11-08 at 14 30 44

**Comment by RunningLeon** [comment]
> @RunningLeon thanks for your instant reply. I can't run ```python tools/check_env.py?``, for it raises the same problem:
> 
> Screen Shot 2022-11-08 at 14 30 44

@WuChannn That's weird. How do you install the mmdeploy? You should build and install mmdeploy of branch `dev-1.x` from source.

**Comment by WuChannn** [comment]
@RunningLeon  i dowload mmdeploy-0.10.0-linux-x86_64-onnxruntime1.8.1 from https://github.com/open-mmlab/mmdeploy/releases, and use pip install it, then git clone mmdeploy and checkout to dev-1.x

**Comment by RunningLeon** [comment]
> @RunningLeon i dowload mmdeploy-0.10.0-linux-x86_64-onnxruntime1.8.1 from https://github.com/open-mmlab/mmdeploy/releases, and use pip install it, then git clone mmdeploy and checkout to dev-1.x

@WuChannn Hi, there's no mmdeploy's released version based on dev-1.x. You could build and install mmdeploy:dev-1.x from source

**Comment by WuChannn** [comment]
@RunningLeon so if i want to use mmdeploy-0.10.0-linux-x86_64-onnxruntime1.8.1, how can i fit with mmcv 2.0.0rc1 for it does have no Config module.

**Pull request merged**
