### PR TITLE
[Fix] Fix ascend faster-rcnn

### PR DESCRIPTION
**Pull request by grimoire**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
I tried master branch too. But got the following errors:
```
  File "/share/lvhan/mmdeploy/mmdeploy/core/rewriters/rewriter_utils.py", line 402, in wrapper
    return self.func(self, *args, **kwargs)
  File "/share/lvhan/mmdeploy/mmdeploy/pytorch/functions/tensor_getitem.py", line 19, in tensor__getitem__ascend
    return ctx.origin_func(self, key)
IndexError: too many indices for tensor of dimension 1

```

**Comment by grimoire** [comment]
> test error by executing `python demo/python/object_detection.py cpu ../mmdeploy_models/mmdet/faster-rcnn/ascend/ demo/resources/det.jpg` The error log is:
> 
> ```
>  [error] [acl_net.cpp:494] Shape mismatch [1, 3, 1344, 800] vs [1, 3, 800, 1344]
> ```
> 
> The conversion command is:
> 
> ```
>  python tools/deploy.py configs/mmdet/detection/detection_ascend_static-800x1344.py ../checkpoint/faster-rcnn_r50_fpn_1x_coco.py ../checkpoint/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth demo/resources/det.jpg --dump-info --work-dir ../mmdeploy_models/mmdet/faster-rcnn/ascend
> ```

use dynamic deploy config

**Comment by lvhan028** [comment]
> > test error by executing `python demo/python/object_detection.py cpu ../mmdeploy_models/mmdet/faster-rcnn/ascend/ demo/resources/det.jpg` The error log is:
> > ```
> >  [error] [acl_net.cpp:494] Shape mismatch [1, 3, 1344, 800] vs [1, 3, 800, 1344]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The conversion command is:
> > ```
> >  python tools/deploy.py configs/mmdet/detection/detection_ascend_static-800x1344.py ../checkpoint/faster-rcnn_r50_fpn_1x_coco.py ../checkpoint/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth demo/resources/det.jpg --dump-info --work-dir ../mmdeploy_models/mmdet/faster-rcnn/ascend
> > ```
> 
> use dynamic deploy config

Yes. The dynamic config works. Should we still keep the static config?
https://github.com/open-mmlab/mmdeploy/issues/1766 talks about static config

**Review by lvhan028 — APPROVED** [review]
LGTM

**Comment by Tracy-git** [comment]
请问有在最新的mmcv2.0上部署过310p的机器吗

**Pull request merged**
