### PR TITLE
When you install the torchvision with the problem of no module named torch, you can try this method.

### PR DESCRIPTION
**Pull request by lijoe123**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
  **When i install the torchvision in the jetpack 5.0+ with `pip install -e .` ,** 
image

**it occur the problem**
image

## Modification

 You can try the command  `pip install -e . --no-build-isolation`.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
Sorry, I didn't get it.
Seems this PR is not related to the motivation

**Comment by lijoe123** [comment]
> Sorry, I didn't get it. Seems this PR is not related to the motivation

I'm sorry  , I don't know how to write PR.

**Comment by lvhan028** [comment]
> > Sorry, I didn't get it. Seems this PR is not related to the motivation
> 
> I'm sorry , I don't know how to write PR.

That's all right. Let me find an appropriate way later

**Comment by OpenMMLab-Assistant005** [comment]
Hi @lijoe123 ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
