### PR TITLE
【Docs】fix docs

### PR DESCRIPTION
**Pull request by VVsssssk**
## Motivation
Fix Readme docs link.
Fix codebase docs model config.

### CODE REVIEW

**Comment by SingleZombie** [comment]
The "MMDeploy" logo in Chinese readthedocs links to English readthedocs homepage (https://mmdeploy.readthedocs.io/zh_CN/latest/). Could you fix it in this PR?

**Comment by VVsssssk** [comment]
> The "MMDeploy" logo in Chinese readthedocs links to English readthedocs homepage (https://mmdeploy.readthedocs.io/zh_CN/latest/). Could you fix it in this PR?

**Review by SingleZombie — APPROVED** [review]
LGTM

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
