### PR TITLE
[Fix] Fix display bugs for windows

### PR DESCRIPTION
**Pull request by hanrui1sensetime**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix display bugs for windows, refer to #330 

## Modification

We check the platform and the environment at the same time.

## BC-breaking (Optional)

None.

## Use cases (Optional)

None.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by grimoire** [comment]
Did that mean the visualization will always be called even when it is on a headless window device?

**Comment by hanrui1sensetime** [comment]
> Did that mean the visualization will always be called even when it is on a headless window device?

In what occasion will use headless windows device?

**Comment by grimoire** [comment]
> In what occasion will use headless windows device?

I don't know. Theoretically headless windows did exist. Can we assume our user would never use it?

**Review by grimoire — APPROVED** [review]

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by lvhan028** [comment]
Can a result image 'ouput_pytorch.jpg' and 'output_tensorrt.jpg' be output?

**Comment by hanrui1sensetime** [comment]
> Can a result image 'ouput_pytorch.jpg' and 'output_tensorrt.jpg' be output?

No, tkinter will failed when in headless device.

**Pull request merged**
