### PR TITLE
fix mmdet ONNXRuntime cuda test bug

### PR DESCRIPTION
**Pull request by NagatoYuki0943**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix mmdet ONNXRuntime cuda test bug.
Some error happended when I test the yolox speed.
```
python tools/test.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    ../mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py \
    --model work_dir/det/yolox-s-ort-dynamic/end2end.onnx \
    --speed-test \
    --log2file work_dir/det/yolox-s-ort-dynamic/logs-cuda.txt \
    --device cuda:0
```
error
```
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

## Modification

Under the line https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/codebase/mmdet/deploy/object_detection_model.py#L210 add this code could solve the question.
```python
dets = dets.to(device=torch.device(self.device))
```

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
@NagatoYuki0943, I think there are probably similar issues in other codebase modules in `mmdeploy/codebase/*`. Could you help check it?

@grimoire should we take where-the-tensor-is into consideration in our new API design?

**Comment by NagatoYuki0943** [comment]
@[lvhan028](https://github.com/lvhan028)

I test the mmcls mmseg and mmocr onnxruntime-gpu speed.
mmcls and mmseg test OK but the mmocr‘s speed is very slow.
I will test other codebases if I have time.

> mmcls convnext-tiny 
```python
python tools/test.py \
>     configs/mmcls/classification_onnxruntime_dynamic.py \
>     ../mmclassification/configs/convnext/convnext-tiny_32xb128_in1k_self.py \
>     --model work_dir/self/convnext-tiny/end2end.onnx \
>     --speed-test \
>     --log2file work_dir/self/convnext-tiny/logs-cuda.txt \
>     --device cuda:1
[2022-05-06 13:45:23.697] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-05-06 13:45:24,213 - mmdeploy - INFO - Sorting the dataset by 'height' and 'width' is not possible.
2022-05-06 13:45:24,215 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             /home/ubuntu/Program/mm/mmdeploy/build/lib/libmmdeploy_onnxruntime_ops.so
[>                                                 ] 109/3000, 39.0 task/s, elapsed: 3s, ETA:    74s2022-05-06 13:45:29,746 - test - INFO - [__ort_execute]-110 times per count: 14.96 ms, 66.82 FPS
[>>>                                               ] 209/3000, 48.0 task/s, elapsed: 4s, ETA:    58s2022-05-06 13:45:31,301 - test - INFO - [__ort_execute]-210 times per count: 15.08 ms, 66.31 FPS
[>>>>>                                             ] 309/3000, 52.4 task/s, elapsed: 6s, ETA:    51s2022-05-06 13:45:32,849 - test - INFO - [__ort_execute]-310 times per count: 15.12 ms, 66.15 FPS
[>>>>>>                                            ] 409/3000, 54.7 task/s, elapsed: 7s, ETA:    47s2022-05-06 13:45:34,433 - test - INFO - [__ort_execute]-410 times per count: 15.22 ms, 65.68 FPS
[>>>>>>>>                                          ] 509/3000, 56.2 task/s, elapsed: 9s, ETA:    44s2022-05-06 13:45:36,013 - test - INFO - [__ort_execute]-510 times per count: 15.28 ms, 65.44 FPS
[>>>>>>>>>>                                        ] 609/3000, 56.9 task/s, elapsed: 11s, ETA:    42s2022-05-06 13:45:37,645 - test - INFO - [__ort_execute]-610 times per count: 15.40 ms, 64.92 FPS
[>>>>>>>>>>>                                       ] 709/3000, 57.6 task/s, elapsed: 12s, ETA:    40s2022-05-06 13:45:39,260 - test - INFO - [__ort_execute]-710 times per count: 15.47 ms, 64.65 FPS
[>>>>>>>>>>>>>                                     ] 809/3000, 57.9 task/s, elapsed: 14s, ETA:    38s2022-05-06 13:45:40,914 - test - INFO - [__ort_execute]-810 times per count: 15.57 ms, 64.24 FPS
[>>>>>>>>>>>>>>>                                   ] 909/3000, 58.1 task/s, elapsed: 16s, ETA:    36s2022-05-06 13:45:42,621 - test - INFO - [__ort_execute]-910 times per count: 15.68 ms, 63.76 FPS
[>>>>>>>>>>>>>>>>                                  ] 1009/3000, 58.1 task/s, elapsed: 17s, ETA:    34s2022-05-06 13:45:44,311 - test - INFO - [__ort_execute]-1010 times per count: 15.77 ms, 63.42 FPS
[>>>>>>>>>>>>>>>>>>                                ] 1109/3000, 58.1 task/s, elapsed: 19s, ETA:    33s2022-05-06 13:45:46,023 - test - INFO - [__ort_execute]-1110 times per count: 15.86 ms, 63.05 FPS
[>>>>>>>>>>>>>>>>>>>>                              ] 1209/3000, 58.2 task/s, elapsed: 21s, ETA:    31s2022-05-06 13:45:47,706 - test - INFO - [__ort_execute]-1210 times per count: 15.91 ms, 62.84 FPS
[>>>>>>>>>>>>>>>>>>>>>                             ] 1309/3000, 58.3 task/s, elapsed: 22s, ETA:    29s2022-05-06 13:45:49,417 - test - INFO - [__ort_execute]-1310 times per count: 15.98 ms, 62.58 FPS
[>>>>>>>>>>>>>>>>>>>>>>>                           ] 1409/3000, 58.3 task/s, elapsed: 24s, ETA:    27s2022-05-06 13:45:51,135 - test - INFO - [__ort_execute]-1410 times per count: 16.04 ms, 62.34 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>                         ] 1509/3000, 58.3 task/s, elapsed: 26s, ETA:    26s2022-05-06 13:45:52,835 - test - INFO - [__ort_execute]-1510 times per count: 16.08 ms, 62.19 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>                        ] 1609/3000, 58.3 task/s, elapsed: 28s, ETA:    24s2022-05-06 13:45:54,565 - test - INFO - [__ort_execute]-1610 times per count: 16.13 ms, 61.98 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>                      ] 1709/3000, 58.3 task/s, elapsed: 29s, ETA:    22s2022-05-06 13:45:56,281 - test - INFO - [__ort_execute]-1710 times per count: 16.18 ms, 61.82 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                    ] 1809/3000, 58.3 task/s, elapsed: 31s, ETA:    20s2022-05-06 13:45:57,987 - test - INFO - [__ort_execute]-1810 times per count: 16.21 ms, 61.70 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                   ] 1909/3000, 58.3 task/s, elapsed: 33s, ETA:    19s2022-05-06 13:45:59,720 - test - INFO - [__ort_execute]-1910 times per count: 16.25 ms, 61.54 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 2009/3000, 58.2 task/s, elapsed: 35s, ETA:    17s2022-05-06 13:46:01,466 - test - INFO - [__ort_execute]-2010 times per count: 16.30 ms, 61.36 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>               ] 2109/3000, 58.1 task/s, elapsed: 36s, ETA:    15s2022-05-06 13:46:03,255 - test - INFO - [__ort_execute]-2110 times per count: 16.36 ms, 61.13 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>              ] 2209/3000, 58.0 task/s, elapsed: 38s, ETA:    14s2022-05-06 13:46:05,034 - test - INFO - [__ort_execute]-2210 times per count: 16.41 ms, 60.95 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>            ] 2309/3000, 57.9 task/s, elapsed: 40s, ETA:    12s2022-05-06 13:46:06,803 - test - INFO - [__ort_execute]-2310 times per count: 16.45 ms, 60.79 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>          ] 2409/3000, 57.9 task/s, elapsed: 42s, ETA:    10s2022-05-06 13:46:08,567 - test - INFO - [__ort_execute]-2410 times per count: 16.48 ms, 60.67 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>         ] 2509/3000, 57.8 task/s, elapsed: 43s, ETA:     8s2022-05-06 13:46:10,356 - test - INFO - [__ort_execute]-2510 times per count: 16.52 ms, 60.51 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>       ] 2609/3000, 57.7 task/s, elapsed: 45s, ETA:     7s2022-05-06 13:46:12,141 - test - INFO - [__ort_execute]-2610 times per count: 16.56 ms, 60.38 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>     ] 2709/3000, 57.7 task/s, elapsed: 47s, ETA:     5s2022-05-06 13:46:13,917 - test - INFO - [__ort_execute]-2710 times per count: 16.59 ms, 60.26 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>    ] 2809/3000, 57.6 task/s, elapsed: 49s, ETA:     3s2022-05-06 13:46:15,680 - test - INFO - [__ort_execute]-2810 times per count: 16.62 ms, 60.17 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  ] 2909/3000, 57.6 task/s, elapsed: 51s, ETA:     2s2022-05-06 13:46:17,486 - test - INFO - [__ort_execute]-2910 times per count: 16.66 ms, 60.04 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3000/3000, 57.5 task/s, elapsed: 52s, ETA:     0s/home/ubuntu/Program/mm/mmdeploy/mmdeploy/codebase/mmcls/deploy/classification.py:242: UserWarning: Evaluation metrics are not specified.
  warnings.warn('Evaluation metrics are not specified.')
2022-05-06 13:46:19,099 - test - INFO - the predicted result for the first element is pred_score = 0.56, pred_label = 0 and pred_class = buildings. Specify --out to save all results to files.
```

> mmseg segformer_b2
```python
python tools/test.py \
>     configs/mmseg/segmentation_onnxruntime_dynamic.py \
>     ../mmsegmentation/configs/segformer/segformer_mit-b2_512x512_20k_voc12_self.py \
>     --model work_dir/self/segformer_b2-ort-dynamic/end2end.onnx \
>     --speed-test \
>     --log-interval 20 \
>     --log2file work_dir/self/segformer_b2-ort-dynamic/logs-cuda.txt \
>     --device cuda:1
[2022-05-06 14:07:33.221] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
2022-05-06 14:07:33,299 - mmseg - INFO - Loaded 281 images
2022-05-06 14:07:33,299 - mmdeploy - INFO - Sorting the dataset by 'height' and 'width' is not possible.
2022-05-06 14:07:33,331 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             /home/ubuntu/Program/mm/mmdeploy/build/lib/libmmdeploy_onnxruntime_ops.so
[>>>>>                                             ] 29/281, 4.8 task/s, elapsed: 6s, ETA:    53s2022-05-06 14:07:42,722 - test - INFO - [__ort_execute]-30 times per count: 62.58 ms, 15.98 FPS
[>>>>>>>>                                          ] 49/281, 5.8 task/s, elapsed: 8s, ETA:    40s2022-05-06 14:07:45,074 - test - INFO - [__ort_execute]-50 times per count: 61.30 ms, 16.31 FPS
[>>>>>>>>>>>>                                      ] 69/281, 6.5 task/s, elapsed: 11s, ETA:    33s2022-05-06 14:07:47,344 - test - INFO - [__ort_execute]-70 times per count: 60.91 ms, 16.42 FPS
[>>>>>>>>>>>>>>>                                   ] 89/281, 6.9 task/s, elapsed: 13s, ETA:    28s2022-05-06 14:07:49,616 - test - INFO - [__ort_execute]-90 times per count: 60.74 ms, 16.46 FPS
[>>>>>>>>>>>>>>>>>>>                               ] 109/281, 7.1 task/s, elapsed: 15s, ETA:    24s2022-05-06 14:07:51,913 - test - INFO - [__ort_execute]-110 times per count: 61.10 ms, 16.37 FPS
[>>>>>>>>>>>>>>>>>>>>>>                            ] 129/281, 7.4 task/s, elapsed: 18s, ETA:    21s2022-05-06 14:07:54,181 - test - INFO - [__ort_execute]-130 times per count: 61.12 ms, 16.36 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>                        ] 149/281, 7.5 task/s, elapsed: 20s, ETA:    18s2022-05-06 14:07:56,443 - test - INFO - [__ort_execute]-150 times per count: 61.18 ms, 16.35 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                    ] 169/281, 7.7 task/s, elapsed: 22s, ETA:    15s2022-05-06 14:07:58,736 - test - INFO - [__ort_execute]-170 times per count: 61.43 ms, 16.28 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 189/281, 7.8 task/s, elapsed: 24s, ETA:    12s2022-05-06 14:08:00,987 - test - INFO - [__ort_execute]-190 times per count: 61.45 ms, 16.27 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>             ] 209/281, 7.9 task/s, elapsed: 27s, ETA:     9s2022-05-06 14:08:03,235 - test - INFO - [__ort_execute]-210 times per count: 61.44 ms, 16.28 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>          ] 229/281, 8.0 task/s, elapsed: 29s, ETA:     7s2022-05-06 14:08:05,466 - test - INFO - [__ort_execute]-230 times per count: 61.35 ms, 16.30 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>      ] 249/281, 8.0 task/s, elapsed: 31s, ETA:     4s2022-05-06 14:08:07,690 - test - INFO - [__ort_execute]-250 times per count: 61.27 ms, 16.32 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   ] 269/281, 8.1 task/s, elapsed: 33s, ETA:     1s2022-05-06 14:08:10,056 - test - INFO - [__ort_execute]-270 times per count: 61.25 ms, 16.33 FPS
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 281/281, 8.1 task/s, elapsed: 35s, ETA:     0s(mm) 
```

> mmocr dbnet  **very slow**
```python
python tools/test.py \
> configs/mmocr/text-detection/text-detection_onnxruntime_dynamic.py \
>     ../mmocr/configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py \
>     --model work_dir/ocr/dbnet-ort-dynamic/end2end.onnx \
>     --speed-test \
>     --log2file work_dir/ocr/dbnet-ort-dynamic/logs-cuda.txt \
>     --device cuda:1
[2022-05-06 15:16:23.556] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2022-05-06 15:16:28,232 - mmdeploy - INFO - Sorting the dataset by 'height' and 'width' is not possible.
2022-05-06 15:16:28,264 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             /home/ubuntu/Program/mm/mmdeploy/build/lib/libmmdeploy_onnxruntime_ops.so
[>                                                 ] 12/500, 0.0 task/s, elapsed: 2004s, ETA: 81510s
```

**Comment by lvhan028** [comment]
Thank you very much, @NagatoYuki0943. 
So it seems this issue only happens in mmdet onnxruntime cuda test and no other codebase suffers.

**Review by irexyc — APPROVED** [review]

**Review by grimoire — APPROVED** [review]

**Comment by lvhan028** [comment]
ci will be fixed in PR #441

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @NagatoYuki0943 ！First of all, we want to express our gratitude for your significant PR in the mmdeploy project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
