### PR TITLE
feat(third_party): remove manually install spdlog

### PR DESCRIPTION
**Pull request by tpoisonooo**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Remove manually install spdlog.

## Modification

* Add third_party/spdlog
* Add build option  `MMDEPLOY_SUBMODULE_SPDLOG`
  * default value is ON, use **header-only** third_party/spdlog
    * because `spdlog CMakeLists.txt` also use `BUILD_SHARED_LIBS`, user have to specifiy libspdlog.so path
  * if OFF,  use must specifiy spdlog cmake path
* Fix build demo error when `MMDEPLOY_CODEBASES="mmcls"`
* Remove relative doc

## BC-breaking (Optional)

No break change.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by lvhan028 — COMMENTED** [review]
build failed.
```plaintext
/home/PJLAB/lvhan/Documents/projects/open-mmlab/mmdeploy/csrc/core/logger.cpp: In function ‘void mmdeploy::LoadEnvLevels()’:
/home/PJLAB/lvhan/Documents/projects/open-mmlab/mmdeploy/csrc/core/logger.cpp:30:15: error: ‘set_level’ is not a member of ‘spdlog’
       spdlog::set_level(spdlog::level::trace);
               ^~~~~~~~~
/home/PJLAB/lvhan/Documents/projects/open-mmlab/mmdeploy/csrc/core/logger.cpp:32:15: error: ‘set_level’ is not a member of ‘spdlog’
       spdlog::set_level(spdlog::level::debug);
               ^~~~~~~~~
/home/PJLAB/lvhan/Documents/projects/open-mmlab/mmdeploy/csrc/core/logger.cpp:34:15: error: ‘set_level’ is not a member of ‘spdlog’
       spdlog::set_level(spdlog::level::info);
               ^~~~~~~~~
```

**Comment by lvhan028** [comment]
Besides adding spdlog as one of mmdeploy's submodule, I think it's better for us to keep installing spdlog as an option. 
Because Users probably make use of spdlog in their projects too. 
If mmdeploy wouldn't support spdlog prebuilt package, it is likely to bring in conflicts on spdlog if users try to integrate mmdeploy to their projects.

**Comment by tpoisonooo** [comment]
> Besides adding spdlog as one of mmdeploy's submodule, I think it's better for us to keep installing spdlog as an option. Because Users probably make use of spdlog in their projects too. If mmdeploy wouldn't support spdlog prebuilt package, it is likely to bring in conflicts on spdlog if users try to integrate mmdeploy to their projects.

Fixed it after update spdlog version (v2.x --> v1.8.1)

**Comment by irexyc** [comment]
Can't build on windows.  There are some errors like

image

**Comment by tpoisonooo** [comment]
> Can't build on windows. There are some errors like
> 

* Fixed with
  * Add `set_directory_properties` followed by [this answer](https://answers.ros.org/question/251156/unable-to-solve-nvcc-fatal-a-single-input-file-is-required-for-a-non-link-phase-when-an-outputfile-is-specified-error/)
  * Update spdlog to 1.9.2 which is sync with dev-v0.5.0 branch
* win11 + onnxruntime also tested

**Comment by tpoisonooo** [comment]
> > Besides adding spdlog as one of mmdeploy's submodule, I think it's better for us to keep installing spdlog as an option. Because Users probably make use of spdlog in their projects too. If mmdeploy wouldn't support spdlog prebuilt package, it is likely to bring in conflicts on spdlog if users try to integrate mmdeploy to their projects.
> 
> @lvhan028 I was thinking this too. When I started using MMDeploy, I had issues integrating it with our existing code where we had used spdlog as a submodule. I got inspired by the approach done by MMdeploy and I ended up removing spdlog submodule from our project and using the installed package itself. That made it much easier and everything worked.

Yes now `MMDEPLOY_SUBMODULE_SPDLOG` is an option.

**Pull request closed without merging**
