### PR TITLE
[Improve] Improve dockerfile pip source

### PR DESCRIPTION
**Pull request by PeterH0323**
## Motivation

When using `USE_SRC_INSIDE=true` the pip source still the original. Since the user want to use `USE_SRC_INSIDE` so we need to switch the source of pip as well

## Modification

Add pip source. And speed up the download for pip . 🚀

### CODE REVIEW

**Comment by AllentDan** [comment]
Hi, the same to the CPU dockerfile please.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Review by AllentDan — APPROVED** [review]
LGTM

**Comment by lvhan028** [comment]
@PeterH0323 Could you please pull another PR to the master branch?

**Pull request merged**
