### PR TITLE
update mmcv installation

### PR DESCRIPTION
**Pull request by RunningLeon**
## Motivation

Update mmcv installation as in mmtracking [PR](https://github.com/open-mmlab/mmtracking/pull/409)

## Modification

Update mmcv installation in CI and documents.

## BC-breaking (Optional)

None

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by AllentDan — COMMENTED** [review]
Shall we make the version limitation to toch or mmcv in `requirements`

**Comment by RunningLeon** [comment]
> Shall we make the version limitation to toch or mmcv in `requirements`?

Not necessary. `mmcv-full` is installed outside requirements.txt

**Review by AllentDan — APPROVED** [review]
LGTM

**Review by lvhan028 — APPROVED** [review]
LGTM

**Pull request merged**
