### PR TITLE
Update flake8 to GitHub in pre-commit

### PR DESCRIPTION
**Pull request by zhiqwang**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Unified pre-commit tools to GH server.

## Modification

Update the flake8 to GH in pre-commit

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by RunningLeon** [comment]
@zhiqwang Hi, thanks for you contribution. Could you explicitly explain your motivation and benefit from this change?

**Comment by zhiqwang** [comment]
> Hi, thanks for you contribution. Could you explicitly explain your motivation and benefit from this change?

Hi @RunningLeon This is just suggested by the pre-commit and flake8 now, you can check their docs: https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework

**Review by grimoire — APPROVED** [review]
LGTM!
Sounds reasonable. Should we notify other repos to do the same modification? @RunningLeon

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
