### PR TITLE
support mmrazor

### PR DESCRIPTION
**Pull request by LKJacky**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Modification

We add a new Codebase to support mmrazor. Besides, we modify build_task_processor to detect mmrazor config.

### CODE REVIEW

**Comment by lvhan028** [comment]
Hi, @LKJacky Could you share a test example?

**Comment by LKJacky** [comment]
Please install mmrazor form https://github.com/LKJacky/mmrazor/tree/core)](https://github.com/LKJacky/mmrazor/tree/core

Then, run ./projects/group_fisher/configs/mmcls/vgg/deploy.sh

**Comment by grimoire** [comment]
Where is ./work_dirs/vgg_group_fisher_finetune/best_accuracy/top1_epoch_142.pth

**Comment by LKJacky** [comment]
@grimoire  It is in my disk. You can use any checkpoint as it is able to run no matter whether a right checkpoint loaded.

**Review by grimoire — APPROVED** [review]
LGTM

**Comment by irexyc** [comment]
Hi [LKJacky](https://github.com/LKJacky)
where is  `./projects/group_fisher/configs/mmcls/vgg/deploy.sh`

**Comment by LKJacky** [comment]
@irexyc This file had been removed. Please pull dev-1.x branch of mmrazor, and run following commands to test this pr.
```
razor_config=configs/pruning/mmcls/group_fisher/mobilenet/group_fisher_act_deploy_mobilenet-v2_8xb32_in1k.py
deploy_config=mmdeploy/configs/mmcls/classification_onnxruntime_dynamic.py

python mmdeploy/tools/deploy.py $deploy_config \
    $razor_config \
    https://download.openmmlab.com/mmrazor/v1/pruning/group_fisher/mobilenet/act/group_fisher_act_finetune_mobilenet-v2_8xb32_in1k.pth \
    mmdeploy/tests/data/tiger.jpeg \
    --work-dir ./work_dirs/mmdeploy

python mmdeploy/tools/profiler.py $deploy_config \
    $razor_config \
    mmdeploy/demo/resources \
    --model ./work_dirs/mmdeploy/end2end.onnx \
    --shape 224x224 \
    --device cpu \
    --num-iter 1000 \
    --warmup 100
```

**Review by irexyc — APPROVED** [review]

**Pull request merged**
