### PR TITLE
CodeCamp2023-670

### PR DESCRIPTION
**Pull request by shuyaoyimei**
… platform

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Suport more backend on windows

## Modification

Update the document of building mmdeploy with ncnn backend on Windows platform

## BC-breaking (Optional)

None

## Use cases (Optional)

None

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by RunningLeon** [comment]
@shuyaoyimei hi, pls sign the cla and fix lint if possible.

**Comment by shuyaoyimei** [comment]
@RunningLeon hi, all of them are done.

**Comment by RunningLeon** [comment]
@shuyaoyimei hi, lint still fails...

**Comment by shuyaoyimei** [comment]
@RunningLeon hi, the lint error has been fixed  after execute `pre-commit run --all-files`

**Review by RunningLeon — APPROVED** [review]
LGTM

**Review by irexyc — APPROVED** [review]

**Pull request merged**
