### PR TITLE
[Docs] add switch-language

### PR DESCRIPTION
**Pull request by SingleZombie**
## Motivation

We don't have Chinese docs now.

## Modification

- Scale up the logo.
- Update the project links in readthedocs.
- Add switch language function.

### CODE REVIEW

**Comment by gaotongxiao** [comment]
We don't need to configure the "Project" and "OpenMMLab" columns. Using the shared menu would be fine. Ref: https://github.com/open-mmlab/mmocr/pull/655

**Comment by SingleZombie** [comment]
> We don't need to configure the "Project" and "OpenMMLab" columns. Using the shared menu would be fine. Ref: [open-mmlab/mmocr#655](https://github.com/open-mmlab/mmocr/pull/655)

OK. I think we should update the Feishu document about the readthedocs, too.

**Comment by grimoire** [comment]
Can we make the background of image transparent?

**Review by grimoire — APPROVED** [review]

**Review by AllentDan — APPROVED** [review]
LGTM

**Pull request merged**
