### PR TITLE
[Feature] Add mmpose configs for compatibility with Hourglass model in ncnn backend

### PR DESCRIPTION
**Pull request by Qingrenn**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

- The added configs aim to support Hourglass pose-detection model in ncnn backend.
- Hourglass model needs explicit input shape with 256x256 or 384x384.
- Hourglass model can be quantitized to int8 successfully in ncnn backend.

The mmpose config of Hourglass mode is in:
- [hourglass52_coco_256x256](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_256x256.py)
- [hourglass52_coco_384x384](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_384x384.py)

Quantizations results are shown in:
- [Hourgalss quantitization results](https://github.com/Qingrenn/mmdeploy-summer-camp/blob/main/week4/result.md)

## Modification

Add mmpose configs for compatibility with Hourglass model in ncnn backend.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by tpoisonooo** [comment]
看起来不需要配置写 4 份，只是参数动的话。写一个就行。

**Comment by Qingrenn** [comment]
OK, I will keep only one config and remove the others.

**Review by tpoisonooo — APPROVED** [review]
LGTM.

**Review by AllentDan — APPROVED** [review]
LGTM

**Pull request merged**
